language: android
sudo: true
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    - extra-android-m2repository
    - extra-google-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6
  - mkdir -p "${ANDROID_HOME}/licenses"
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
  - cat "${ANDROID_HOME}/licenses/android-sdk-license"
  - export NDK_VERSION=r12e
  - curl -L http://dl.google.com/android/ndk/android-ndk-${NDK_VERSION}-linux-x86_64.bin -O
  - chmod u+x android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - ./android-ndk-${NDK_VERSION}-linux-x86_64.bin > /dev/null
  - rm android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-${NDK_VERSION}
  - export PATH=${ANDROID_NDK_HOME}:${PATH}

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
